### ISSUE TITLE
Cant join server with this mod added

### ISSUE THREAD

**Issue by IchigoGames** [Maciej916/Industrial-Reborn#3] opened 2020-04-26 00:00 UTC
**Describe the bug**
was looking at addeding this to my pack but when i try to join server with this mod added i get this msg. see pic below and it kicks me.

**To Reproduce**
1.not sure just added this mod to modpack then started server
2.no issue joining without this mod..

**Expected behavior**
to be able to join server with this mod added
![Capture](https://user-images.githubusercontent.com/11888162/80293681-f65cb800-8726-11ea-85ed-6cd317e5218a.PNG)

**Versions**
- **Industrial Reborn**:Industrial-Reborn-1.15.2-0.3.0
- **Forge**: forge 31.1.49

**Comment by IchigoGames** [comment] 2020-04-26 03:41
![Capture](https://user-images.githubusercontent.com/11888162/80297085-cbce2780-8745-11ea-8d48-841b79d8dc4c.PNG)
[logs.zip](https://github.com/Maciej916/Industrial-Reborn/files/4534575/logs.zip)

**Comment by Maciej916** [comment] 2020-04-26 16:21
I'll look into it!

**Comment by IchigoGames** [comment] 2020-04-26 20:17
ok without random patches i get msg from pic above with it installed and this mod i get this msg
![Capture](https://user-images.githubusercontent.com/11888162/80318622-029d4f80-87d1-11ea-95ec-51a83f07021d.PNG)

**Comment by IchigoGames** [comment] 2020-04-27 04:27
this may be a issue due to me having a lot of mods 190 in the pack some one i talk to who makes mod says this msg is ether the packet size is to large or the way the packet are handed is wrong so i think this is more of a randompatches issue. so i will close this.

**Comment by Maciej916** [comment] 2020-04-27 06:23
I tested it yesterday and this issue is caused by my mod (bug with crafting recipe packet). I'll release fix today. 😀

**Comment by Maciej916** [comment] 2020-04-27 08:09
Fixed in [v0.3.2](https://www.curseforge.com/minecraft/mc-mods/industrial-reborn/files/2941756)

**Closed by Maciej916** 2020-04-27 08:09 UTC
Labels: bug
